payload

```
45000002D778010000000000000F627566666572206F76657272656164000200010000009254686973206973206D6F7374206C696B656C7920612062756720696E204564676544422E20506C6561736520636F6E7369646572206F70656E696E6720616E206973737565207469636B65742061742068747470733A2F2F6769746875622E636F6D2F6564676564622F6564676564622F6973737565732F6E65773F74656D706C6174653D6275675F7265706F72742E6D6401010000021B54726163656261636B20286D6F737420726563656E742063616C6C206C617374293A0A202046696C6520226564622F7365727665722F70726F746F636F6C2F62696E6172792E707978222C206C696E6520313739372C20696E206564622E7365727665722E70726F746F636F6C2E62696E6172792E45646765436F6E6E656374696F6E2E6D61696E0A202046696C6520226564622F7365727665722F70726F746F636F6C2F62696E6172792E707978222C206C696E65203436392C20696E20617574680A202046696C6520226564622F7365727665722F70726F746F636F6C2F62696E6172792E707978222C206C696E65203537372C20696E20646F5F68616E647368616B650A202046696C6520226564622F7365727665722F706770726F746F2F2E2F6275666665722E707978222C206C696E65203435342C20696E206564622E7365727665722E706770726F746F2E706770726F746F2E526561644275666665722E726561645F6C656E5F70726566697865645F757466380A202046696C6520226564622F7365727665722F706770726F746F2F2E2F6275666665722E707978222C206C696E65203432302C20696E206564622E7365727665722E706770726F746F2E706770726F746F2E526561644275666665722E726561645F62797465730A6564622E7365727665722E706770726F746F2E706770726F746F2E4275666665724572726F723A20627566666572206F766572726561640A

---

"E\0\0\u0002�x\u0001\0\0\0\0\0\0\u000fbuffer overread\0\u0002\0\u0001\0\0\0�This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md\u0001\u0001\0\0\u0002\u001bTraceback (most recent call last):\n  File \"edb/server/protocol/binary.pyx\", line 1797, in edb.server.protocol.binary.EdgeConnection.main\n  File \"edb/server/protocol/binary.pyx\", line 469, in auth\n  File \"edb/server/protocol/binary.pyx\", line 577, in do_handshake\n  File \"edb/server/pgproto/./buffer.pyx\", line 454, in edb.server.pgproto.pgproto.ReadBuffer.read_len_prefixed_utf8\n  File \"edb/server/pgproto/./buffer.pyx\", line 420, in edb.server.pgproto.pgproto.ReadBuffer.read_bytes\nedb.server.pgproto.pgproto.BufferError: buffer overread\n"
```
